### ISSUE TITLE
[Question] Firezone Gateway runs as root

### ISSUE THREAD

**Issue by sdaberdaku** [Intuinewin/helm-charts#42]
Hello @Intuinewin,

Sorry for bothering you again. 

I noticed that the Firezone Gateway is the only component that runs as root. The security context is defined so I was wondering if this was an intended behavior or nor.

Thanks again for your patience and the awesome work you did with these charts!

Best, 

Sebastian

**Comment by Intuinewin** [comment]
Hello, yes this is an intended behavior: I was not able to start the container without running it as root.
The SecurityContext is overridable if you want to try. If you manage to get it working, feel free to submit a PR.

**Comment by sdaberdaku** [comment]
I spent a couple of hours today testing various combinations of capabilities but to no avail. Probably some intervention in how the docker image is built is needed for this to work.
